# Generated by Django 5.0.3 on 2024-03-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afroholichome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_image', models.ImageField(upload_to='static/images/project/')),
                ('artist_name', models.CharField(max_length=25)),
                ('work_name', models.CharField(max_length=25)),
            ],
        ),
    ]
