# Generated by Django 5.0.3 on 2024-05-30 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afroholichome', '0003_subscriber_first_name_alter_project_project_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='upcomingproject2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=25)),
                ('song_name', models.CharField(max_length=25)),
                ('project_image', models.ImageField(upload_to='static/images/project/ ')),
            ],
        ),
        migrations.RenameModel(
            old_name='project',
            new_name='upcomingproject1',
        ),
        migrations.RenameField(
            model_name='upcomingproject1',
            old_name='work_name',
            new_name='song_name',
        ),
    ]
