# Generated by Django 5.0.3 on 2024-05-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afroholichome', '0004_upcomingproject2_rename_project_upcomingproject1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='static/images/news/ ')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
