# Generated by Django 5.0.3 on 2024-06-04 14:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afroholichome', '0005_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingproject1',
            name='link',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upcomingproject2',
            name='link',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='static/images/news/'),
        ),
        migrations.AlterField(
            model_name='upcomingproject1',
            name='project_image',
            field=models.ImageField(upload_to='static/images/project/'),
        ),
        migrations.AlterField(
            model_name='upcomingproject2',
            name='project_image',
            field=models.ImageField(upload_to='static/images/project/'),
        ),
    ]
