# Generated by Django 5.0.3 on 2024-06-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afroholichome', '0006_upcomingproject1_link_upcomingproject2_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingproject1',
            name='artist_name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='upcomingproject2',
            name='artist_name',
            field=models.CharField(max_length=15),
        ),
    ]
