# Generated by Django 5.0.3 on 2024-06-11 15:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afroholichome', '0008_merch1_merch2'),
    ]

    operations = [
        migrations.AddField(
            model_name='merch1',
            name='merch_description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merch1',
            name='merch_price',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merch2',
            name='merch_description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merch2',
            name='merch_price',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
